SELECT 
    ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM 
    FISH_INFO;
    
# 다른 풀이
# WITH FISH_INFO_REVISED AS (
# SELECT COALESCE(LENGTH, 10) AS LENGTH
# FROM FISH_INFO
# ) 
# SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
# FROM FISH_INFO_REVISED;