# -- JOIN 만 사용
# SELECT COUNT(*) AS FISH_COUNT, FNI.FISH_NAME
# FROM FISH_INFO FI
# JOIN FISH_NAME_INFO FNI
#     ON FI.FISH_TYPE = FNI.FISH_TYPE
# GROUP BY FNI.FISH_NAME
# ORDER BY FISH_COUNT DESC;

-- CTE 사용
WITH FISHCOUNT AS (
    SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT C.FISH_COUNT AS FISH_COUNT, I.FISH_NAME
FROM FISHCOUNT C
LEFT JOIN FISH_NAME_INFO I
    ON C.FISH_TYPE = I.FISH_TYPE
ORDER BY FISH_COUNT DESC;