WITH FISHCOUNT AS (
    SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT C.FISH_COUNT AS FISH_COUNT, I.FISH_NAME AS FISH_NAME
FROM FISHCOUNT C
LEFT JOIN FISH_NAME_INFO I
    ON C.FISH_TYPE = I.FISH_TYPE
ORDER BY FISH_COUNT DESC;