WITH MAX_ECOLIS AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_ECOLI_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT M.YEAR, (M.MAX_ECOLI_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN MAX_ECOLIS M
    ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY M.YEAR, YEAR_DEV