-- CTE를 두개 만든 쿼리
WITH SUMSCORE AS (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
),
MAXSCORE AS (
    SELECT MAX(SCORE) AS MAX_SCORE
    FROM SUMSCORE
)
SELECT
    SUMSCORE.SCORE,
    HR_EMPLOYEES.EMP_NO,
    HR_EMPLOYEES.EMP_NAME,
    HR_EMPLOYEES.POSITION,
    HR_EMPLOYEES.EMAIL
FROM SUMSCORE
JOIN HR_EMPLOYEES
    ON SUMSCORE.EMP_NO = HR_EMPLOYEES.EMP_NO
WHERE SUMSCORE.SCORE = (SELECT MAX_SCORE FROM MAXSCORE)

# -- 최댓값은 1개라는 점을 활용하여 LIMIT 1을 이용한 쿼리
# -- 22년 개별 사원들의 평가점수의 합.
# WITH SUMSCORE AS (
#     SELECT SUM(SCORE) AS SCORE, EMP_NO
#     FROM HR_GRADE
#     GROUP BY EMP_NO
#     ORDER BY SCORE DESC
#     LIMIT 1
# )
# SELECT 
#     S.SCORE AS SCORE, 
#     E.EMP_NO AS EMP_NO, 
#     E.EMP_NAME AS EMP_NAME, 
#     E.POSITION AS POSITION, 
#     E.EMAIL AS EMAIL
# FROM HR_EMPLOYEES E
# JOIN SUMSCORE S
#     ON E.EMP_NO = S.EMP_NO;