-- 22년 개별 사원들의 평가점수의 합.
WITH SUMSCORE AS (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)
SELECT 
    S.SCORE AS SCORE, 
    E.EMP_NO AS EMP_NO, 
    E.EMP_NAME AS EMP_NAME, 
    E.POSITION AS POSITION, 
    E.EMAIL AS EMAIL
FROM HR_EMPLOYEES E
JOIN SUMSCORE S
    ON E.EMP_NO = S.EMP_NO;